### ISSUE TITLE
Help: Titles of some sections in the Help view are black also when using the dark theme

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#1884]
**Describe the bug**
Titles are black and can't be seen in the black background.

Affects at least "See also" and "More results" titles in the context-aware help information.

**To Reproduce**
- Activate the _Dark theme_
- Open the _Help_ (`F1`)

**Expected behavior**
The title should be in white (or is it gray?) like the text above it.

**Screenshots**
![Image](https://github.com/user-attachments/assets/06e80e58-2142-48b6-aff2-ad4eb1993445)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS

**Comment by vogella** [comment]
Adding @BeckerWdf who worked on help styling in the past IIRC

**Comment by fedejeanne** [comment]
I'm debugging `ContextHelperPart::addCategory` and I see that the resulting HTML is

```html
<p><span color="org.eclipse.ui.forms.TITLE">See also:</span></p>
```
Deleting the `color` attribute in the `span` does the trick, but that would mean I have to delete it from other places too. I would like to be able to set the color for `org.eclipse.ui.forms.TITLE` instead, I just can't find the way to do it. 

I tried adding this to `e4-dark_ide_colorextensions.css`

```css
ColorDefinition#org.eclipse.ui.forms.TITLE {
	color: #eeeeee;
	category: '#org-eclipse-ui-presentation-default';
	label: url('platform:/plugin/org.eclipse.ui.themes?message=TITLE');
}
```

and I also tried using `-` instead of `.` _i.e._

```css
ColorDefinition#org-eclipse-ui-forms-TITLE {
	color: #eeeeee;
	category: '#org-eclipse-ui-presentation-default';
	label: url('platform:/plugin/org.eclipse.ui.themes?message=TITLE');
}
```

But it doesn't work. I see absolutely no difference in the output.

Any hints?
